### DISCUSSION TITLE
Progress bar or progress notification option?

### DISCUSSION THREAD

**Discussion by polishdataengineer** [writer/writer-framework#148] [Q&A]
Is there a way to force the timer or some other component to work like a progress bar/information point?

I'm invoking some callables and need to wait a few seconds for an execution, so some information on the UI would be helpful to know that something is going on.

**Comment by polishdataengineer** [comment]
This is my current solution that works, but a separate notification component would be something I think many would need:

```python
def callable_with_notification(state):
  """
  Trigger a callable with a custom notification
  """
  start_time = time.time()
  generation_in_progress = True
  while generation_in_progress:
    state["generation_status"] = "Generation in progress"
    # Your callable
    time.sleep(10)
    end_time = time.time()
    generation_in_progress = False
    generation_time = end_time - start_time

  state["generation_status"] = "Generation completed"
  time.sleep(3)
  state["generation_status"] = False
```

next we need to have a proper `loader` css class (defined in a custom css file):
```css
.loader {
  border: 16px solid #f3f3f3; /* Light grey */
  border-top: 16px solid red; /* Blue */
  border-radius: 50%;
  width: 20px;
  height: 20px;
  animation: spin 2s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
```

On the UI we choose the `Button` component and two `Text` fields:
![image](https://github.com/streamsync-cloud/streamsync/assets/69598075/93a0b70e-d078-4e20-bf67-fe9ec92f30ae)

We assign the `callable_with_notification` to the `Button`:
![image](https://github.com/streamsync-cloud/streamsync/assets/69598075/1706c84a-03c3-49ef-ba28-9ae59d65a73d)

To the first `Text` component we pass the custom css class:
![image](https://github.com/streamsync-cloud/streamsync/assets/69598075/d9ae815c-69a3-4adc-adb2-46c3ff39188c)

To the second `Text` component we pass the `state["generation_status"]` variable:
![image](https://github.com/streamsync-cloud/streamsync/assets/69598075/1390c503-6aca-425d-b8e8-9c8a2edaae6a)

and finally for those two `Text` components we need to change the visibility, to check the `state["generation_status"]` variable:
![image](https://github.com/streamsync-cloud/streamsync/assets/69598075/f1e1a683-83bd-4a6d-909a-ffd0fb198b76)

After that, we can test it by hitting our generation `Button`:
![ezgif-4-5b134c5e25](https://github.com/streamsync-cloud/streamsync/assets/69598075/fc25ad94-2ee0-47ef-a81e-f2f776637430)

The spinning loader and message will appear when the `Button` is clicked and the callable inside is executed.
